# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-fontcacheproto
Summary:    X.Org X11 Protocol fontcacheproto
Version:    0.1.3
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/fontcacheproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-fontcacheproto.yaml
Provides:   fontcacheproto


%description
This extension defines a protocol to allow client control over the caching
of server-side core fonts.




%prep
%setup -q -n fontcacheproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/fontcacheproto.pc
%{_includedir}/X11/extensions/fontcachstr.h
%{_includedir}/X11/extensions/fontcache.h
%{_includedir}/X11/extensions/fontcacheP.h
# << files


